spring.application.name=petcarehub-java
server.port=8080

spring.datasource.url=jdbc:h2:mem:petcarehub;MODE=Oracle;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.cache.type=caffeine
spring.cache.cache-names=protocolos,pets,scores
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
