spring.application.name=petcarehub-java
server.port=8080

spring.datasource.url=${DB_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
spring.datasource.username=${DB_USERNAME:PETCARE}
spring.datasource.password=${DB_PASSWORD:petcare123}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.cache.type=caffeine
spring.cache.cache-names=protocolos,pets,scores
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
